Update comments to Sphinx documentation format
Zhaoyilunnn/qdao pull request #18
Opened 2024-07-28 09:11 UTC by raunakkumarsingh

2024-07-29 03:02 UTC, Zhaoyilunnn requested changes
Hello @raunakkumarsingh , thanks for the help. Most docstrings look good to me. It would be better to make some additional changes before I merge your PR.
1. Sometimes `NP (np)` and `NL (nl)` are illustrated as `number of partitions` and `number of layers`. However, in qdao, they consistently represent `number of primary qubits` and `number of local qubits`
2. Please check the docstrings with class attributes, sometimes they are just class members or variables not belong to this class.
3. Please check the `qdao/qiskit` directory, most files are qiskit source code. I put them in qdao since I need to do some tricky changes in qiskit source code to make it work correctly with qdao. For these qiskit codes, I suggest not to change their original docstrings.

2024-07-29 03:04 UTC, Zhaoyilunnn commented
Please ignore the unit test failing. This is due to qiskit version conflict and I have fixed it https://github.com/Zhaoyilunnn/qdao/commit/6675a9866d3ef38f473aab7dc5442d2ce074a511

2024-08-04 08:55 UTC, raunakkumarsingh commented
I resolved all issues. Can you confirm if there are any other changes needed?

2024-08-05 01:25 UTC, Zhaoyilunnn approved these changes

2024-08-05 01:26 UTC, merged